#!/usr/bin/env python

import asyncio
import json
import websockets
import uuid
import random
import os
import base64
import threading
import time
import subprocess
import signal
import atexit
from collections import defaultdict
from auth_manager import AuthManager
from constants import (
    USER_TEXTURE_DIR, USER_DATA_DIR, PLACES_DIR, WORLD_ENVIRONMENT_FILE,
    VOICE_CHAT_SERVER_URL, VOICE_CHAT_SERVER_PORT, MAIN_SERVER_PORT,
    MAIN_SERVER_HOST, MAIN_SERVER_URL, PLACE_SERVER_START_PORT, 
    MAX_MESSAGE_SIZE, MAX_QUEUE_SIZE, PLOTS_DATA_DIR, PLOTS_CONFIG_FILE,
    EXTERNAL_DOMAIN
)
from texture_manager import (
    get_texture_filename, user_has_texture, send_texture_data, get_texture_path, 
    save_decal_texture, get_available_flags, flag_exists, send_flag_texture_data,
    get_flag_texture_path
)
from user_manager import (
    get_user_accessories, get_user_character_type, save_user_character_type,
    load_user_data, save_user_data, get_user_monsters, set_user_monsters, add_user_monster
)
from plot_manager import (
    load_plots_config, load_plot_objects, save_plot_objects,
    can_user_place_object, get_all_plot_objects, get_plot_info_for_client
)
from chat_filter import filter_chat_message, reload_filter

# Store connected clients and their data
clients = {}
next_id = 1
auth_manager = AuthManager()
# Replicated objects state: net_id -> {"transform": {...}}
objects = {}
# Monster replication: net_id -> {"species": str, "position": {...}, "rotation": {...}, "owner_id": int}
monsters = {}
# Player monster ownership: username -> [{"species": str, "texture": str}, ...]
player_monsters = {}  # Loaded from JSON file

# ============================================================================
# Web-to-Game Single Sign-On (SSO) Token System
# ============================================================================
# Tokens are generated by the website when a logged-in user wants to play
# the Godot game. The game (HTML5 export) receives the token via JavaScript
# and sends it to authenticate without needing to re-enter credentials.
#
# Token format: base64(username:timestamp:signature)
# The signature is HMAC-SHA256 of "username:timestamp" with the shared secret.
# This allows the website to generate tokens and the game server to validate
# them without needing shared storage.
# ============================================================================
import hmac
import hashlib
from constants import SSO_SECRET_KEY, SSO_TOKEN_EXPIRY_SECONDS

# Track used tokens to prevent replay attacks (tokens are one-time use)
used_tokens = set()

def generate_sso_token(username):
    """Generate a signed SSO token for web-to-game authentication.
    
    Token format: base64(username:timestamp:signature)
    """
    timestamp = str(int(time.time()))
    message = f"{username}:{timestamp}"
    signature = hmac.new(
        SSO_SECRET_KEY.encode(), 
        message.encode(), 
        hashlib.sha256
    ).hexdigest()
    
    token_data = f"{username}:{timestamp}:{signature}"
    token = base64.b64encode(token_data.encode()).decode()
    
    print(f"[SSO] Generated token for {username} (expires in {SSO_TOKEN_EXPIRY_SECONDS}s)")
    return token

def validate_sso_token(token):
    """Validate an SSO token. Returns username if valid, None otherwise.
    
    Validates:
    1. Token format is correct
    2. Signature matches (token wasn't tampered with)
    3. Token hasn't expired
    4. Token hasn't been used before (one-time use)
    """
    try:
        # Decode the token
        token_data = base64.b64decode(token).decode()
        parts = token_data.split(':')
        
        if len(parts) != 3:
            print(f"[SSO] Invalid token format")
            return None
        
        username, timestamp_str, provided_signature = parts
        
        # Check if token was already used
        if token in used_tokens:
            print(f"[SSO] Token already used for {username}")
            return None
        
        # Verify signature
        message = f"{username}:{timestamp_str}"
        expected_signature = hmac.new(
            SSO_SECRET_KEY.encode(),
            message.encode(),
            hashlib.sha256
        ).hexdigest()
        
        if not hmac.compare_digest(provided_signature, expected_signature):
            print(f"[SSO] Invalid signature for token")
            return None
        
        # Check expiry
        timestamp = int(timestamp_str)
        now = int(time.time())
        
        if now - timestamp > SSO_TOKEN_EXPIRY_SECONDS:
            print(f"[SSO] Token expired for {username}")
            return None
        
        # Mark token as used (prevent replay attacks)
        used_tokens.add(token)
        
        # Clean up old used tokens periodically (keep last 1000)
        if len(used_tokens) > 1000:
            # Remove oldest entries (simple approach - just clear when too many)
            used_tokens.clear()
        
        print(f"[SSO] Token validated for {username}")
        return username
        
    except Exception as e:
        print(f"[SSO] Token validation error: {e}")
        return None

# Plot system
plots_config = {}  # Will be loaded on startup
plot_objects = {}  # plot_id -> {net_id -> object_data}

# Place server management
# Please note that Place Servers are unused in Metaversum-Salihanum. 
# Places are a ROBLOX like private place, think like alternative dimension/universe.
# It is nevertheless included and not commented out for future use,
# or for any project that may be based on this codebase.

place_servers = {}  # place_name -> {"port": int, "process": subprocess.Popen, "url": str}
next_place_port = PLACE_SERVER_START_PORT

# Ensure directories exist
os.makedirs(USER_TEXTURE_DIR, exist_ok=True)
os.makedirs(USER_DATA_DIR, exist_ok=True)
os.makedirs(PLACES_DIR, exist_ok=True)
os.makedirs(PLOTS_DATA_DIR, exist_ok=True)

# Load plots configuration
plots_config = load_plots_config()
print(f"Loaded {len(plots_config)} plots from configuration")

# Load all plot objects
plot_objects = get_all_plot_objects(plots_config)
total_plot_objects = sum(len(objs) for objs in plot_objects.values())
print(f"Loaded {total_plot_objects} objects across all plots")

# Integrated Voice Chat Server
class VoiceChatServer:
    def __init__(self, port=3246):
        self.port = port
        self.clients = {}  # websocket -> client_info
        self.rooms = defaultdict(set)  # room_id -> set of websockets
        self.ping_interval = 3  # Send ping every 3 seconds
        self.ping_tasks = {}  # websocket -> ping task
        
    async def start_ping_task(self, websocket):
        """Start periodic ping for a client"""
        async def ping_loop():
            try:
                while websocket in self.clients:
                    await asyncio.sleep(self.ping_interval)
                    if websocket in self.clients:
                        try:
                            await websocket.send(json.dumps({"type": "ping"}))
                        except websockets.exceptions.ConnectionClosed:
                            break
                        except Exception as e:
                            print(f"Error sending ping: {e}")
                            break
            except asyncio.CancelledError:
                pass
        
        task = asyncio.create_task(ping_loop())
        self.ping_tasks[websocket] = task
        return task
    
    async def register_client(self, websocket, client_info):
        """Register a new client"""
        self.clients[websocket] = client_info
        room_id = client_info.get('room', 'default')
        self.rooms[room_id].add(websocket)
        
        # Start ping task for this client
        await self.start_ping_task(websocket)
        
        print(f"Voice client registered: {client_info['username']} in room '{room_id}' ({len(self.clients)} total)")
        
        # Notify room about new user
        await self.broadcast_to_room(room_id, {
            "type": "user_joined",
            "username": client_info['username'],
            "timestamp": int(time.time() * 1000)
        }, exclude=websocket)
    
    async def unregister_client(self, websocket):
        """Unregister a client"""
        if websocket in self.clients:
            client_info = self.clients[websocket]
            room_id = client_info.get('room', 'default')
            
            # Cancel ping task
            if websocket in self.ping_tasks:
                self.ping_tasks[websocket].cancel()
                del self.ping_tasks[websocket]
            
            # Remove from room and clients
            self.rooms[room_id].discard(websocket)
            del self.clients[websocket]
            
            print(f"Voice client unregistered: {client_info['username']} from room '{room_id}' ({len(self.clients)} remaining)")
            
            # Notify room about user leaving
            await self.broadcast_to_room(room_id, {
                "type": "user_left", 
                "username": client_info['username'],
                "timestamp": int(time.time() * 1000)
            })
    
    async def broadcast_to_room(self, room_id, message, exclude=None):
        """Broadcast message to all clients in a room"""
        if room_id not in self.rooms:
            return
            
        room_clients = self.rooms[room_id].copy()
        if exclude:
            room_clients.discard(exclude)
            
        if not room_clients:
            return
            
        message_json = json.dumps(message)
        disconnected = set()
        
        # Send to all clients in room
        for client_ws in room_clients:
            try:
                await client_ws.send(message_json)
            except websockets.exceptions.ConnectionClosed:
                disconnected.add(client_ws)
            except Exception as e:
                print(f"Error sending to voice client: {e}")
                disconnected.add(client_ws)
        
        # Clean up disconnected clients
        for ws in disconnected:
            await self.unregister_client(ws)
    
    async def handle_audio_chunk(self, websocket, data):
        """Handle incoming audio chunk and redistribute"""
        if websocket not in self.clients:
            return
            
        client_info = self.clients[websocket]
        room_id = client_info.get('room', 'default')
        
        # Add sender info to the audio chunk
        audio_message = {
            "type": "audio_chunk",
            "username": client_info['username'],
            "audio_data": data['audio_data'],
            "timestamp_ms": data.get('timestamp_ms', int(time.time() * 1000)),
            "chunk_info": data.get('chunk_info', {})
        }
        
        # Broadcast to all clients in room (including sender for echo/monitoring)
        await self.broadcast_to_room(room_id, audio_message)
    
    async def handle_client(self, websocket):
        """Handle individual client connection"""
        client_info = None
        try:
            # Wait for registration message
            registration_msg = await websocket.recv()
            registration_data = json.loads(registration_msg)
            
            if registration_data.get('type') != 'register':
                await websocket.send(json.dumps({"type": "error", "message": "First message must be registration"}))
                return
            
            client_info = {
                'username': registration_data.get('username', 'Anonymous'),
                'room': registration_data.get('room', 'default'),
                'user_type': registration_data.get('user_type', 'player')  # 'player' or 'streamer'
            }
            
            await self.register_client(websocket, client_info)
            
            # Send confirmation
            await websocket.send(json.dumps({
                "type": "registered",
                "username": client_info['username'],
                "room": client_info['room']
            }))
            
            # Handle messages
            async for message in websocket:
                try:
                    data = json.loads(message)
                    
                    if data.get('type') == 'audio_chunk':
                        await self.handle_audio_chunk(websocket, data)
                    elif data.get('type') == 'ping':
                        await websocket.send(json.dumps({"type": "pong"}))
                    elif data.get('type') == 'pong':
                        # Client responded to our ping - connection is alive
                        pass
                    else:
                        print(f"Unknown voice message type: {data.get('type')}")
                        
                except json.JSONDecodeError:
                    print("Received invalid JSON from voice client")
                except Exception as e:
                    print(f"Error handling voice message: {e}")
                    
        except websockets.exceptions.ConnectionClosed:
            pass
        except Exception as e:
            print(f"Error in voice client handler: {e}")
        finally:
            if client_info:
                await self.unregister_client(websocket)

    async def start_server(self, ssl_context=None):
        """Start the voice chat server"""
        protocol = "wss" if ssl_context else "ws"
        print(f"Starting Voice Chat Server on port {self.port}")
        
        async with websockets.serve(self.handle_client, "0.0.0.0", self.port, ssl=ssl_context):
            print(f"Voice Chat Server listening on {protocol}://0.0.0.0:{self.port}")
            await asyncio.Future()  # Run forever

# Global voice chat server instance
voice_chat_server = VoiceChatServer(VOICE_CHAT_SERVER_PORT)

# Function to read world environment configuration
def get_world_environment():
    """Read the world environment configuration from JSON file"""
    if not os.path.exists(WORLD_ENVIRONMENT_FILE):
        # Default environment
        return {"weather": {"type": "clear"}}
    
    try:
        with open(WORLD_ENVIRONMENT_FILE, "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"Error reading world environment: {e}")
        return {"weather": {"type": "clear"}}

# Function to broadcast weather updates to all clients  
async def broadcast_weather_update():
    """Send current weather state to all connected clients"""
    world_env = get_world_environment()
    weather_data = world_env.get("weather", {"type": "clear"})
    
    print(f"Broadcasting weather update: {weather_data}")
    
    # Send to all connected clients
    for client_id, client in clients.items():
        try:
            await client["websocket"].send(json.dumps({
                "type": "weather_update",
                "weather": weather_data
            }))
        except Exception as e:
            print(f"Error sending weather update to client {client_id}: {e}")

# Place server management functions
def get_place_scene_path(place_name):
    """Get the path to a place scene file"""
    return os.path.join(PLACES_DIR, f"{place_name}.tscn")

def place_scene_exists(place_name):
    """Check if a place scene file exists"""
    return os.path.exists(get_place_scene_path(place_name))

def read_place_scene(place_name):
    """Read a place scene file"""
    path = get_place_scene_path(place_name)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return None

async def spawn_place_server(place_name):
    """Spawn a new place server for the given place"""
    global next_place_port
    
    if place_name in place_servers:
        print(f"Place server '{place_name}' already running")
        return place_servers[place_name]
    
    # Check if place scene exists
    if not place_scene_exists(place_name):
        print(f"Place scene '{place_name}' not found")
        return None
    
    # Assign a port
    port = next_place_port
    next_place_port += 1
    
    # Spawn the place server process
    try:
        process = subprocess.Popen(
            ["python", "place_server.py", place_name, str(port)],
            cwd=os.getcwd(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        
        # Wait a moment for the server to start
        await asyncio.sleep(1)
        
        # Store the server info
        server_info = {
            "port": port,
            "process": process,
            "url": f"wss://{EXTERNAL_DOMAIN}:{port}",
            "place_name": place_name
        }
        place_servers[place_name] = server_info
        
        print(f"Spawned place server '{place_name}' on port {port}")
        return server_info
    except Exception as e:
        print(f"Error spawning place server: {e}")
        return None

async def get_or_spawn_place_server(place_name):
    """Get existing place server or spawn a new one"""
    if place_name in place_servers:
        return place_servers[place_name]
    return await spawn_place_server(place_name)

def cleanup_place_servers():
    """Kill all spawned place server processes"""
    print("\nShutting down all place servers...")
    for place_name, server_info in place_servers.items():
        try:
            process = server_info["process"]
            print(f"  Terminating place server: {place_name} (port {server_info['port']})")
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()
        except Exception as e:
            print(f"  Error terminating place server {place_name}: {e}")
    print("All place servers stopped.")

# Register cleanup function
atexit.register(cleanup_place_servers)

async def handle_client(websocket):
    global next_id
    
    # Assign client ID
    client_id = next_id
    next_id += 1
    
    # Initial position (random within a small area, spawn 10 units up)
    position = {
        "x": random.uniform(-5, 5),
        "y": 10,
        "z": random.uniform(-5, 5)
    }
    rotation = {"x": 0, "y": 0, "z": 0}
    
    # Store client data (initially not authenticated)
    clients[client_id] = {
        "websocket": websocket,
        "username": f"Guest{client_id}",
        "authenticated": False,
        "position": position,
        "rotation": rotation,
        "texture": None,  # Will be set when authenticated
        "character_type": "humanoid"  # Default character type
    }
    
    # Send connected message to client with voice chat server info
    await websocket.send(json.dumps({
        "type": "connected",
        "client_id": client_id,
        "username": clients[client_id]["username"],
        "authenticated": False,
        "character_type": clients[client_id]["character_type"],
        "voice_chat_server": VOICE_CHAT_SERVER_URL
    }))
    
    # Send list of existing players to the new client
    players_list = []
    for existing_id, existing_client in clients.items():
        if existing_id != client_id:  # Don't include the new client
            player_data = {
                "id": existing_id,
                "username": existing_client["username"],
                "position": existing_client["position"],
                "rotation": existing_client["rotation"],
                "texture": existing_client["texture"],
                "accessories": existing_client.get("accessories", []),
                "character_type": existing_client.get("character_type", "humanoid"),
                "emotion": existing_client.get("emotion", "neutral")
            }
            # Include flag_code for countryball_oneside players
            if existing_client.get("character_type") == "countryball_oneside":
                player_data["flag_code"] = existing_client.get("flag_code", "")
            players_list.append(player_data)
            
    await websocket.send(json.dumps({
        "type": "player_list",
        "players": players_list
    }))
    
    # Send texture data for all existing players to the new client
    for existing_id, existing_client in clients.items():
        if existing_id != client_id and existing_client.get("texture"):
            existing_username = existing_client["username"]
            existing_character_type = existing_client.get("character_type", "countryball")
            
            # Handle countryball_oneside with flag texture separately
            if existing_character_type == "countryball_oneside":
                flag_code = existing_client.get("flag_code", "")
                if flag_code:
                    await send_flag_texture_data(existing_username, flag_code, [clients[client_id]])
            else:
                await send_texture_data(existing_username, existing_character_type, [clients[client_id]])

    # Send existing replicated objects to the new client
    for net_id, obj in objects.items():
        await websocket.send(json.dumps({
            "type": "object_spawn",
            "net_id": net_id,
            "transform": obj.get("transform", {})
        }))
    
    # Send existing monsters to the new client
    for net_id, monster_data in monsters.items():
        await websocket.send(json.dumps({
            "type": "monster_spawn",
            "monster_data": {
                "net_id": net_id,
                "species": monster_data.get("species", "countryball"),
                "position": monster_data.get("position", {"x": 0, "y": 0, "z": 0}),
                "rotation": monster_data.get("rotation", {"x": 0, "y": 0, "z": 0}),
                "texture": monster_data.get("texture", "")
            }
        }))
    
    # Send plot information to the new client
    plots_info = get_plot_info_for_client(plots_config)
    await websocket.send(json.dumps({
        "type": "plots_info",
        "plots": plots_info
    }))
    
    # Send all plot objects to the new client
    for plot_id, objects_dict in plot_objects.items():
        for net_id, obj in objects_dict.items():
            await websocket.send(json.dumps({
                "type": "plot_object_spawn",
                "plot_id": plot_id,
                "net_id": net_id,
                "transform": obj.get("transform", {}),
                "object_type": obj.get("object_type", "unknown")
            }))
    
    # Send current weather state to the new client
    world_env = get_world_environment()
    weather_data = world_env.get("weather", {"type": "clear"})
    await websocket.send(json.dumps({
        "type": "weather_update",
        "weather": weather_data
    }))

    # Send default countryball.png texture to all clients (including new guest)
    # This gives guests a default appearance
    #guest_username = clients[client_id]["username"]
    #await send_texture_data(guest_username, "countryball", clients.values())
    #clients[client_id]["texture"] = guest_username  # Mark as having texture
    #print(f"Sent default countryball.png for guest: {guest_username}")
    
    # Notify existing clients about new player
    for existing_id, existing_client in clients.items():
        if existing_id != client_id:  # Don't send to the new client
            await existing_client["websocket"].send(json.dumps({
                "type": "player_joined",
                "player_id": client_id,
                "username": clients[client_id]["username"],
                "position": clients[client_id]["position"],
                "rotation": clients[client_id]["rotation"],
                "texture": clients[client_id]["texture"],
                "accessories": clients[client_id].get("accessories", []),
                "character_type": clients[client_id]["character_type"]
            }))
    
    try:
        async for message in websocket:
            data = json.loads(message)
            
            # Remove voice chat message handling - these will go to the voice server
            # Keep all other message types (register, login, transform_update, chat_message, etc.)
            
            # Handle authentication requests
            if data["type"] == "register":
                username = data["username"]
                password = data["password"]
                
                success, message = auth_manager.register_user(username, password)
                
                await websocket.send(json.dumps({
                    "type": "register_response",
                    "success": success,
                    "message": message
                }))
            
            elif data["type"] == "login":
                username = data["username"]
                password = data["password"]
                
                success, result = auth_manager.authenticate_user(username, password)
                
                if success:
                    # Update client data with authenticated user
                    old_username = clients[client_id]["username"]
                    clients[client_id]["username"] = username
                    clients[client_id]["authenticated"] = True
                    clients[client_id]["display_name"] = result["display_name"]
                    
                    # Get user's accessories
                    accessories = get_user_accessories(username)
                    clients[client_id]["accessories"] = accessories
                    print(f"User {username} has accessories: {accessories}")  # Debug print
                    
                    # Get user's character type
                    character_type = get_user_character_type(username)
                    clients[client_id]["character_type"] = character_type
                    print(f"User {username} has character type: {character_type}")  # Debug print
                    
                    # Load flag_code for countryball_oneside users
                    flag_code = None
                    if character_type == "countryball_oneside":
                        user_data = load_user_data(username)
                        flag_code = user_data.get("flag_code", "")
                        clients[client_id]["flag_code"] = flag_code
                        print(f"User {username} has flag_code: {flag_code}")
                    
                    # First notify all clients about the name change
                    for cid, client in clients.items():
                        await client["websocket"].send(json.dumps({
                            "type": "system_message",
                            "message": f"{old_username} is now known as {username}"
                        }))
                    
                    # Send texture data based on character type
                    clients[client_id]["texture"] = username
                    
                    if character_type == "countryball_oneside" and flag_code:
                        # Send flag texture for countryball_oneside
                        success, actual_flag_code = await send_flag_texture_data(
                            username, flag_code, clients.values()
                        )
                        if success:
                            print(f"Sent flag texture {actual_flag_code} for {username}")
                        else:
                            print(f"Failed to send flag texture for {username}, flag_code: {flag_code}")
                    else:
                        # THEN check if user has a custom texture for their character type and send it AFTER the username change
                        has_texture = user_has_texture(username, character_type)
                        
                        # Always send texture data (either custom or default countryball.png)
                        await send_texture_data(username, character_type, clients.values())
                        
                        if has_texture:
                            print(f"Sent custom {character_type} texture for {username}")
                        else:
                            print(f"Sent default countryball.png for {username} (no custom texture found)")
                    
                    # Send accessories information to ALL clients - even if empty list
                    print(f"Sending accessories to all clients: {accessories}")  # Debug print
                    for cid, client in clients.items():
                        await client["websocket"].send(json.dumps({
                            "type": "accessories_data",
                            "player_id": client_id,  # Add player_id for easier matching
                            "username": username,
                            "accessories": accessories
                        }))
                    
                    # Send character type information to ALL clients
                    print(f"Sending character type to all clients: {character_type}")  # Debug print
                    transform_data = {
                        "type": "character_transform",
                        "player_id": client_id,
                        "username": username,
                        "character_type": character_type
                    }
                    if character_type == "countryball_oneside" and flag_code:
                        transform_data["flag_code"] = flag_code
                    
                    for cid, client in clients.items():
                        await client["websocket"].send(json.dumps(transform_data))
                
                await websocket.send(json.dumps({
                    "type": "login_response",
                    "success": success,
                    "message": "Login successful" if success else result
                }))
            
            # Web-to-Game SSO: Token-based login (no password needed)
            elif data["type"] == "token_login":
                token = data.get("token", "")
                
                # 1. Validate the SSO token
                username = validate_sso_token(token)
                
                if username:
                    # 2. Check if the user file (e.g., salih1.json) exists
                    user_data = auth_manager.get_user_data(username)
                    
                    # 3. IF MISSING: Create the file immediately - Gemini force added this and would not function without it.
                    if not user_data:
                        print(f"[SSO] File for {username} missing. Auto-creating...")
                        import uuid
                        # We register them with a random password to generate the .json file
                        auth_manager.register_user(username, str(uuid.uuid4()))
                        # Now the file exists, so we can load it
                        user_data = auth_manager.get_user_data(username)
                        
                    if user_data:
                        # Update client data with authenticated user
                        old_username = clients[client_id]["username"]
                        clients[client_id]["username"] = username
                        clients[client_id]["authenticated"] = True
                        clients[client_id]["display_name"] = username
                        
                        # Get user's accessories
                        accessories = get_user_accessories(username)
                        clients[client_id]["accessories"] = accessories
                        print(f"[SSO] User {username} has accessories: {accessories}")
                        
                        # Get user's character type
                        character_type = get_user_character_type(username)
                        clients[client_id]["character_type"] = character_type
                        print(f"[SSO] User {username} has character type: {character_type}")
                        
                        # Load flag_code for countryball_oneside users
                        flag_code = None
                        if character_type == "countryball_oneside":
                            sso_user_data = load_user_data(username)
                            flag_code = sso_user_data.get("flag_code", "")
                            clients[client_id]["flag_code"] = flag_code
                            print(f"[SSO] User {username} has flag_code: {flag_code}")
                        
                        # Notify all clients about the name change
                        for cid, client in clients.items():
                            await client["websocket"].send(json.dumps({
                                "type": "system_message",
                                "message": f"{old_username} is now known as {username}"
                            }))
                        
                        # Send texture data based on character type
                        clients[client_id]["texture"] = username
                        
                        if character_type == "countryball_oneside" and flag_code:
                            # Send flag texture for countryball_oneside
                            success, actual_flag_code = await send_flag_texture_data(
                                username, flag_code, clients.values()
                            )
                            if success:
                                print(f"[SSO] Sent flag texture {actual_flag_code} for {username}")
                            else:
                                print(f"[SSO] Failed to send flag texture for {username}, flag_code: {flag_code}")
                        else:
                            await send_texture_data(username, character_type, clients.values())
                        
                        # Send accessories to all clients
                        for cid, client in clients.items():
                            await client["websocket"].send(json.dumps({
                                "type": "accessories_data",
                                "player_id": client_id,
                                "username": username,
                                "accessories": accessories
                            }))
                        
                        # Send character type to all clients
                        transform_data = {
                            "type": "character_transform",
                            "player_id": client_id,
                            "username": username,
                            "character_type": character_type
                        }
                        if character_type == "countryball_oneside" and flag_code:
                            transform_data["flag_code"] = flag_code
                        
                        for cid, client in clients.items():
                            await client["websocket"].send(json.dumps(transform_data))
                        
                        # Send login success
                        await websocket.send(json.dumps({
                            "type": "login_success",
                            "username": username
                        }))
                        
                        await websocket.send(json.dumps({
                            "type": "login_response",
                            "success": True,
                            "message": "SSO login successful"
                        }))
                        
                        print(f"[SSO] Token login successful for {username}")
                    else:
                        await websocket.send(json.dumps({
                            "type": "login_response",
                            "success": False,
                            "message": "User data not found"
                        }))
                else:
                    await websocket.send(json.dumps({
                        "type": "login_response",
                        "success": False,
                        "message": "Invalid or expired token"
                    }))
            
            elif data["type"] == "get_texture":
                # Client is requesting a specific texture
                texture_name = data["texture_name"]
                
                # Find the client with this username to get their character type and flag_code
                target_character_type = "humanoid"  # Default
                target_flag_code = None
                for cid, client_data in clients.items():
                    if client_data["username"] == texture_name:
                        target_character_type = client_data.get("character_type", "humanoid")
                        if target_character_type == "countryball_oneside":
                            target_flag_code = client_data.get("flag_code", "")
                        break
                
                # Handle countryball_oneside with flag texture
                if target_character_type == "countryball_oneside" and target_flag_code:
                    flag_path, actual_flag_code = get_flag_texture_path(target_flag_code)
                    if flag_path:
                        with open(flag_path, "rb") as f:
                            texture_data = base64.b64encode(f.read()).decode('utf-8')
                        
                        await websocket.send(json.dumps({
                            "type": "texture_data",
                            "texture_name": texture_name,
                            "character_type": "countryball_oneside",
                            "flag_code": actual_flag_code,
                            "data": texture_data
                        }))
                        print(f"Sent flag texture {actual_flag_code} for {texture_name}")
                    else:
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": f"Flag texture '{target_flag_code}' not found"
                        }))
                        print(f"Flag texture not found for {texture_name}, flag_code: {target_flag_code}")
                else:
                    # Get the regular texture path
                    texture_path = get_texture_path(texture_name, target_character_type)
                    
                    if texture_path:
                        # Read and encode the texture file
                        with open(texture_path, "rb") as f:
                            texture_data = base64.b64encode(f.read()).decode('utf-8')
                        
                        # Send texture data to the client with correct character type
                        await websocket.send(json.dumps({
                            "type": "texture_data",
                            "texture_name": texture_name,
                            "character_type": target_character_type,  # Send the correct character type
                            "data": texture_data
                        }))
                        print(f"Sent {target_character_type} texture for {texture_name}")
                    else:
                        # Texture not found
                        texture_filename = get_texture_filename(texture_name, target_character_type)
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": f"Texture {texture_filename} not found"
                        }))
                        print(f"Texture not found for {texture_name}")
            
            elif data["type"] == "transform_update":
                # Update client position and rotation
                clients[client_id]["position"] = data["position"]
                clients[client_id]["rotation"] = data["rotation"]
                
                # Store model rotation if provided
                model_rotation_y = data.get("model_rotation_y", None)
                
                # Store floor state if provided
                on_floor = data.get("on_floor", True)
                
                # Broadcast to all other clients
                for cid, client in clients.items():
                    if cid != client_id:
                        message = {
                            "type": "player_transform",
                            "player_id": client_id,
                            "position": data["position"],
                            "rotation": data["rotation"],
                            "on_floor": on_floor
                        }
                        
                        # Add model rotation if provided
                        if model_rotation_y is not None:
                            message["model_rotation_y"] = model_rotation_y
                            
                        await client["websocket"].send(json.dumps(message))
            
            elif data["type"] == "chat_message":
                # Get the message
                message = data["message"]
                
                # Check if it's a character transformation command
                if message.startswith("/transform "):
                    parts = message.split(" ")
                    if len(parts) >= 2:
                        character_type = parts[1].lower()
                        if character_type in ["humanoid", "countryball"]:
                            # Get old character type for texture handling
                            old_character_type = clients[client_id]["character_type"]
                            
                            # Update client's character type
                            clients[client_id]["character_type"] = character_type
                            
                            # Save to user data if authenticated
                            if clients[client_id]["authenticated"]:
                                username = clients[client_id]["username"]
                                save_user_character_type(username, character_type)
                                
                                # Check if user has texture for new character type
                                has_texture = user_has_texture(username, character_type)
                                
                                if has_texture:
                                    clients[client_id]["texture"] = username
                                    # Send new texture to all clients with character type info
                                    await send_texture_data(username, character_type, clients.values())
                                    print(f"Sent {character_type} texture for {username} after transformation")
                                else:
                                    clients[client_id]["texture"] = None
                                    print(f"No {character_type} texture found for {username} after transformation")
                            
                            # Broadcast transformation to all clients
                            for cid, client in clients.items():
                                await client["websocket"].send(json.dumps({
                                    "type": "character_transform",
                                    "player_id": client_id,
                                    "username": clients[client_id]["username"],
                                    "character_type": character_type
                                }))
                            
                            # Send confirmation to the user
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Transformed to {character_type}"
                            }))
                            continue
                        else:
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": "Invalid character type. Use 'humanoid' or 'countryball'"
                            }))
                            continue
                
                # Check if it's a countryball command with flag argument
                # /countryball TUR - transforms to countryball_oneside with TUR flag
                # /countryball TUR_republic - uses TUR_republic flag, falls back to TUR if not found
                if message.startswith("/countryball "):
                    parts = message.split(" ", 1)  # Split into at most 2 parts
                    if len(parts) >= 2:
                        flag_code = parts[1].strip()
                        
                        if not flag_code:
                            # No flag code provided, show available flags
                            available_flags = get_available_flags()
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Available flags: {', '.join(sorted(available_flags))}"
                            }))
                            continue
                        
                        # Check if flag exists (with fallback support)
                        if not flag_exists(flag_code):
                            available_flags = get_available_flags()
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Flag '{flag_code}' not found. Available: {', '.join(sorted(available_flags))}"
                            }))
                            continue
                        
                        # Update client's character type to countryball_oneside
                        clients[client_id]["character_type"] = "countryball_oneside"
                        clients[client_id]["flag_code"] = flag_code
                        
                        # Save to user data if authenticated
                        if clients[client_id]["authenticated"]:
                            username = clients[client_id]["username"]
                            save_user_character_type(username, "countryball_oneside")
                            # Also save the flag code in user data
                            user_data = load_user_data(username)
                            user_data["flag_code"] = flag_code
                            save_user_data(username, user_data)
                        
                        # Send flag texture to all clients
                        username = clients[client_id]["username"]
                        success, actual_flag_code = await send_flag_texture_data(
                            username, flag_code, clients.values()
                        )
                        
                        if success:
                            clients[client_id]["texture"] = username
                            print(f"Sent flag texture {actual_flag_code} for {username}")
                            
                            # Notify message if fallback was used
                            fallback_msg = ""
                            if actual_flag_code.lower() != flag_code.lower():
                                fallback_msg = f" ('{flag_code}' not found, using '{actual_flag_code}')"
                            
                            # Broadcast transformation to all clients
                            for cid, client in clients.items():
                                await client["websocket"].send(json.dumps({
                                    "type": "character_transform",
                                    "player_id": client_id,
                                    "username": username,
                                    "character_type": "countryball_oneside",
                                    "flag_code": actual_flag_code
                                }))
                            
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Transformed to countryball with {actual_flag_code} flag{fallback_msg}"
                            }))
                        else:
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Error loading flag texture for '{flag_code}'"
                            }))
                        continue
                
                # Check if it's an emotion command (for countryball characters)
                # /happy, /sad, /serious, /neutral
                valid_emotions = ["happy", "sad", "serious", "neutral"]
                emotion_cmd = message.strip().lower()[1:]  # Remove the leading /
                if emotion_cmd in valid_emotions:
                    # Check if player is a countryball type
                    character_type = clients[client_id].get("character_type", "humanoid")
                    if character_type not in ["countryball", "countryball_oneside"]:
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": "Emotion commands only work for countryball characters. Use /transform countryball first."
                        }))
                        continue
                    
                    # Store the emotion in client state
                    clients[client_id]["emotion"] = emotion_cmd
                    
                    username = clients[client_id]["username"]
                    print(f"Player {username} set emotion to: {emotion_cmd}")
                    
                    # Broadcast emotion change to all clients
                    for cid, client in clients.items():
                        await client["websocket"].send(json.dumps({
                            "type": "emotion_update",
                            "player_id": client_id,
                            "username": username,
                            "emotion": emotion_cmd
                        }))
                    
                    # Send confirmation to the user
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Emotion set to {emotion_cmd}"
                    }))
                    continue
                
                # Check if it's a plot info command
                if message.startswith("/myplot") or message.startswith("/plot"):
                    if not clients[client_id]["authenticated"]:
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": "You must be logged in to view your plot"
                        }))
                        continue
                    
                    username = clients[client_id]["username"]
                    
                    # Find user's plot
                    user_plot_id = None
                    user_plot_data = None
                    for plot_id, plot_data in plots_config.items():
                        if plot_data.get("owner", "").lower() == username.lower():
                            user_plot_id = plot_id
                            user_plot_data = plot_data
                            break
                    
                    if user_plot_data:
                        boundaries = user_plot_data.get("boundaries", {})
                        plot_name = user_plot_data.get("name", user_plot_id)
                        num_objects = len(plot_objects.get(user_plot_id, {}))
                        
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": f"Your plot '{plot_name}': X[{boundaries.get('min_x')}, {boundaries.get('max_x')}] Y[{boundaries.get('min_y')}, {boundaries.get('max_y')}] Z[{boundaries.get('min_z')}, {boundaries.get('max_z')}] - {num_objects} objects placed"
                        }))
                    else:
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": "You don't have a plot assigned. Contact the server administrator."
                        }))
                    continue
                
                # Check if it's a teleport command
                if message.startswith("/teleport "):
                    parts = message.split(" ", 1)  # Split into at most 2 parts to preserve plot names with spaces
                    if len(parts) >= 2:
                        destination = parts[1].lower().strip()
                        
                        # Define teleport destinations
                        teleport_locations = {
                            "asia": {"x": 477, "y": 122, "z": -38},
                            "europe": {"x": -207, "y": 122, "z": 32},
                            "parliament": {"x": 360, "y": 73, "z": -450},
                        }
                        
                        new_position = None
                        teleport_destination_name = None
                        
                        # Check if it's a static teleport location
                        if destination in teleport_locations:
                            new_position = teleport_locations[destination]
                            teleport_destination_name = destination.capitalize()
                        else:
                            # Check if it's a plot name (only if authenticated)
                            if clients[client_id]["authenticated"]:
                                username = clients[client_id]["username"]
                                
                                # Find user's plot by name
                                for plot_id, plot_data in plots_config.items():
                                    plot_owner = plot_data.get("owner", "").lower()
                                    plot_name = plot_data.get("name", "").lower()
                                    
                                    # Check if user owns this plot and name matches
                                    if plot_owner == username.lower() and plot_name == destination:
                                        # Calculate center position of the plot
                                        boundaries = plot_data.get("boundaries", {})
                                        center_x = (boundaries.get("min_x", 0) + boundaries.get("max_x", 0)) / 2
                                        center_y = boundaries.get("min_y", 0) + 5  # Slightly above ground
                                        center_z = (boundaries.get("min_z", 0) + boundaries.get("max_z", 0)) / 2
                                        
                                        new_position = {"x": center_x, "y": center_y, "z": center_z}
                                        teleport_destination_name = plot_data.get("name", plot_id)
                                        break
                        
                        if new_position:
                            # Update client's position
                            clients[client_id]["position"] = new_position
                            
                            # Send confirmation to the user
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": f"Teleported to {teleport_destination_name}"
                            }))
                            
                            # Send teleport command to the client to update their actual position
                            await websocket.send(json.dumps({
                                "type": "teleport",
                                "position": new_position
                            }))
                            
                            # Broadcast new position to all other clients
                            for cid, client in clients.items():
                                if cid != client_id:
                                    await client["websocket"].send(json.dumps({
                                        "type": "player_transform",
                                        "player_id": client_id,
                                        "position": new_position,
                                        "rotation": clients[client_id]["rotation"],
                                        "on_floor": True
                                    }))
                            
                            continue
                        else:
                            await websocket.send(json.dumps({
                                "type": "system_message",
                                "message": "Invalid destination. Use: /teleport asia, /teleport europe, or /teleport <your plot name>"
                            }))
                            continue
                    else:
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": "Usage: /teleport <destination> (asia, europe)"
                        }))
                        continue
                
                # Check if it's any other command
                if message.startswith("/"):
                    # Handle /reloadfilter command (admin only - you can add auth check)
                    if message.strip().lower() == "/reloadfilter":
                        reload_filter()
                        await websocket.send(json.dumps({
                            "type": "system_message",
                            "message": "Chat filter reloaded"
                        }))
                        continue
                    # Handle other commands on the client side
                    continue
                
                # Filter the message for profanity
                username = clients[client_id]["username"]
                allowed, filtered_message, block_reason = filter_chat_message(message, username)
                
                if not allowed:
                    # Message was blocked entirely
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": block_reason or "Message blocked by filter"
                    }))
                    continue
                
                # Broadcast filtered message to all clients
                for cid, client in clients.items():
                    await client["websocket"].send(json.dumps({
                        "type": "chat_message",
                        "player_id": client_id,
                        "username": username,
                        "message": filtered_message
                    }))
            
            elif data["type"] == "get_players":
                # Send list of existing players to the requesting client
                players_list = []
                for existing_id, existing_client in clients.items():
                    if existing_id != client_id:  # Don't include the requesting client
                        player_data = {
                            "id": existing_id,
                            "username": existing_client["username"],
                            "position": existing_client["position"],
                            "rotation": existing_client["rotation"],
                            "texture": existing_client["texture"],
                            "accessories": existing_client.get("accessories", []),
                            "character_type": existing_client.get("character_type", "countryball"),
                            "emotion": existing_client.get("emotion", "neutral")
                        }
                        # Include flag_code for countryball_oneside players
                        if existing_client.get("character_type") == "countryball_oneside":
                            player_data["flag_code"] = existing_client.get("flag_code", "")
                        players_list.append(player_data)
                        
                await websocket.send(json.dumps({
                    "type": "player_list",
                    "players": players_list
                }))
            
            elif data["type"] == "join_place":
                # Handle request to join a place
                place_name = data.get("place_name", "")
                
                if not place_name:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "Invalid place name"
                    }))
                    continue
                
                # Check if place exists
                if not place_scene_exists(place_name):
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Place '{place_name}' does not exist"
                    }))
                    continue
                
                # Get or spawn the place server
                server_info = await get_or_spawn_place_server(place_name)
                
                if not server_info:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Failed to start place server for '{place_name}'"
                    }))
                    continue
                
                # Read the scene data
                scene_data = read_place_scene(place_name)
                
                if not scene_data:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Failed to load scene data for '{place_name}'"
                    }))
                    continue
                
                # Send place info to client
                await websocket.send(json.dumps({
                    "type": "place_info",
                    "place_name": place_name,
                    "server_url": server_info["url"],
                    "scene_data": scene_data
                }))
                
                print(f"Client {client_id} joining place '{place_name}' at {server_info['url']}")
            
            elif data["type"] == "list_places":
                # List available places
                places = []
                if os.path.exists(PLACES_DIR):
                    for filename in os.listdir(PLACES_DIR):
                        if filename.endswith(".tscn"):
                            place_name = filename[:-5]  # Remove .tscn extension
                            places.append(place_name)
                
                await websocket.send(json.dumps({
                    "type": "places_list",
                    "places": places
                }))
            
            elif data["type"] == "upload_place":
                # Handle place upload (requires authentication)
                if not clients[client_id]["authenticated"]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "You must be logged in to upload places"
                    }))
                    continue
                
                username = clients[client_id]["username"]
                scene_data = data.get("scene_data", "")
                
                if not scene_data:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "No scene data provided"
                    }))
                    continue
                
                # Save the place scene file under the username
                place_path = os.path.join(PLACES_DIR, f"{username}.tscn")
                
                try:
                    with open(place_path, "w", encoding="utf-8") as f:
                        f.write(scene_data)
                    
                    scene_size_kb = len(scene_data) / 1024
                    print(f"User {username} uploaded their place: {place_path} ({scene_size_kb:.2f} KB)")
                    
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Successfully uploaded your place ({scene_size_kb:.1f} KB)! Others can join with /join {username}"
                    }))
                except Exception as e:
                    print(f"Error saving place for {username}: {e}")
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "Failed to upload place"
                    }))
            
            elif data["type"] == "upload_decal":
                # Handle decal upload (requires authentication)
                if not clients[client_id]["authenticated"]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "You must be logged in to upload decals"
                    }))
                    continue
                
                username = clients[client_id]["username"]
                character_type = data.get("character_type", "humanoid")
                base64_data = data.get("data", "")
                
                if not base64_data:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "No image data provided"
                    }))
                    continue
                
                # Validate character type
                if character_type not in ["humanoid", "countryball"]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "Invalid character type. Must be 'humanoid' or 'countryball'"
                    }))
                    continue
                
                # Save the decal texture
                success, message, file_path = save_decal_texture(username, character_type, base64_data)
                
                if success:
                    # Update client's character type if needed
                    if clients[client_id].get("character_type") != character_type:
                        clients[client_id]["character_type"] = character_type
                        # Save to user data if authenticated
                        save_user_character_type(username, character_type)
                    
                    # Mark texture as available
                    clients[client_id]["texture"] = username
                    
                    # Send the new texture to all clients
                    await send_texture_data(username, character_type, clients.values())
                    
                    # Broadcast character type change if it changed
                    if clients[client_id].get("character_type") == character_type:
                        for cid, client in clients.items():
                            await client["websocket"].send(json.dumps({
                                "type": "character_transform",
                                "player_id": client_id,
                                "username": username,
                                "character_type": character_type
                            }))
                    
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": message
                    }))
                else:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Failed to upload decal: {message}"
                    }))

            elif data["type"] == "place_plot_object":
                # Handle placing an object in a plot
                if not clients[client_id]["authenticated"]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "You must be logged in to place objects in plots"
                    }))
                    continue
                
                username = clients[client_id]["username"]
                position = data.get("position", {})
                transform = data.get("transform", {})
                object_type = data.get("object_type", "unknown")
                net_id = str(data.get("net_id", uuid.uuid4()))
                
                # Check if user can place object at this position
                can_place, plot_id, reason = can_user_place_object(username, position, plots_config)
                
                if not can_place:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"Cannot place object: {reason}"
                    }))
                    continue
                
                # Add object to plot
                if plot_id not in plot_objects:
                    plot_objects[plot_id] = {}
                
                plot_objects[plot_id][net_id] = {
                    "transform": transform,
                    "object_type": object_type,
                    "placed_by": username,
                    "placed_at": time.time()
                }
                
                # Save plot objects
                save_plot_objects(plot_id, plot_objects[plot_id])
                
                # Broadcast to all clients
                for cid, client in clients.items():
                    await client["websocket"].send(json.dumps({
                        "type": "plot_object_spawn",
                        "plot_id": plot_id,
                        "net_id": net_id,
                        "transform": transform,
                        "object_type": object_type
                    }))
                
                print(f"User {username} placed object {net_id} in plot {plot_id}")
            
            elif data["type"] == "remove_plot_object":
                # Handle removing an object from a plot
                if not clients[client_id]["authenticated"]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "You must be logged in to remove objects from plots"
                    }))
                    continue
                
                username = clients[client_id]["username"]
                net_id = str(data.get("net_id"))
                plot_id = data.get("plot_id")
                
                # Check if plot exists
                if plot_id not in plot_objects or net_id not in plot_objects[plot_id]:
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": "Object not found in plot"
                    }))
                    continue
                
                # Check if user owns the plot
                plot_data = plots_config.get(plot_id, {})
                plot_owner = plot_data.get("owner", "")
                
                if plot_owner.lower() != username.lower():
                    await websocket.send(json.dumps({
                        "type": "system_message",
                        "message": f"You can only remove objects from your own plot"
                    }))
                    continue
                
                # Remove object
                del plot_objects[plot_id][net_id]
                
                # Save plot objects
                save_plot_objects(plot_id, plot_objects[plot_id])
                
                # Broadcast removal to all clients
                for cid, client in clients.items():
                    await client["websocket"].send(json.dumps({
                        "type": "plot_object_remove",
                        "plot_id": plot_id,
                        "net_id": net_id
                    }))
                
                print(f"User {username} removed object {net_id} from plot {plot_id}")
            
            elif data["type"] == "update_plot_object":
                # Handle updating an object in a plot
                if not clients[client_id]["authenticated"]:
                    continue
                
                username = clients[client_id]["username"]
                net_id = str(data.get("net_id"))
                plot_id = data.get("plot_id")
                transform = data.get("transform", {})
                
                # Check if plot exists and user owns it
                if plot_id not in plot_objects or net_id not in plot_objects[plot_id]:
                    continue
                
                plot_data = plots_config.get(plot_id, {})
                plot_owner = plot_data.get("owner", "")
                
                if plot_owner.lower() != username.lower():
                    continue
                
                # Update object transform
                plot_objects[plot_id][net_id]["transform"] = transform
                
                # Save plot objects
                save_plot_objects(plot_id, plot_objects[plot_id])
                
                # Broadcast update to all other clients
                for cid, client in clients.items():
                    if cid != client_id:
                        await client["websocket"].send(json.dumps({
                            "type": "plot_object_update",
                            "plot_id": plot_id,
                            "net_id": net_id,
                            "transform": transform
                        }))

            elif data["type"] == "object_grab":
                net_id = str(data.get("net_id"))
                xf = data.get("transform", {})
                objects[net_id] = {"transform": xf}
                # Broadcast spawn/update to everyone
                for cid, client in clients.items():
                    await client["websocket"].send(json.dumps({
                        "type": "object_spawn",
                        "net_id": net_id,
                        "transform": xf,
                        "seq": data.get("seq", 0),
                        "authority": client_id
                    }))

            elif data["type"] == "object_release":
                net_id = str(data.get("net_id"))
                xf = data.get("transform", {})
                vel = data.get("velocity", {"x": 0, "y": 0, "z": 0})
                objects[net_id] = {"transform": xf}
                # Broadcast update to everyone
                for cid, client in clients.items():
                    await client["websocket"].send(json.dumps({
                        "type": "object_update",
                        "net_id": net_id,
                        "node_path": data.get("node_path", None),
                        "transform": xf,
                        "velocity": vel,
                        "seq": data.get("seq", 0),
                        "authority": client_id
                    }))

            elif data["type"] == "object_update":
                net_id = str(data.get("net_id"))
                xf = data.get("transform", {})
                objects[net_id] = {"transform": xf}
                # Broadcast update to everyone except sender
                for cid, client in clients.items():
                    if cid == client_id:
                        continue
                    await client["websocket"].send(json.dumps({
                        "type": "object_update",
                        "net_id": net_id,
                        "node_path": data.get("node_path", None),
                        "transform": xf,
                        "seq": data.get("seq", 0),
                        "authority": client_id
                    }))
            
            # Monster replication
            elif data["type"] == "monster_spawn":
                monster_data = data.get("monster_data", {})
                net_id = monster_data.get("net_id")
                
                if not net_id:
                    print("Warning: monster_spawn without net_id")
                    continue
                
                # Store monster data (including texture for countryball monsters)
                monsters[net_id] = {
                    "species": monster_data.get("species", "countryball"),
                    "position": monster_data.get("position", {"x": 0, "y": 0, "z": 0}),
                    "rotation": monster_data.get("rotation", {"x": 0, "y": 0, "z": 0}),
                    "texture": monster_data.get("texture", ""),
                    "owner_id": client_id
                }
                
                print(f"Monster spawned: {monsters[net_id]['species']} (net_id: {net_id}, texture: '{monsters[net_id]['texture']}') by client {client_id}")
                
                # Broadcast spawn to all other clients
                for cid, client in clients.items():
                    if cid != client_id:
                        await client["websocket"].send(json.dumps({
                            "type": "monster_spawn",
                            "monster_data": monster_data
                        }))
            
            elif data["type"] == "monster_update":
                monster_data = data.get("monster_data", {})
                net_id = monster_data.get("net_id")
                
                if not net_id:
                    continue
                
                # Update monster data
                if net_id in monsters:
                    monsters[net_id]["position"] = monster_data.get("position", monsters[net_id]["position"])
                    monsters[net_id]["rotation"] = monster_data.get("rotation", monsters[net_id]["rotation"])
                else:
                    # Monster not found, might be out of sync - store it
                    monsters[net_id] = {
                        "species": monster_data.get("species", "countryball"),
                        "position": monster_data.get("position", {"x": 0, "y": 0, "z": 0}),
                        "rotation": monster_data.get("rotation", {"x": 0, "y": 0, "z": 0}),
                        "texture": monster_data.get("texture", ""),
                        "owner_id": client_id
                    }
                
                # Broadcast update to all other clients
                for cid, client in clients.items():
                    if cid != client_id:
                        await client["websocket"].send(json.dumps({
                            "type": "monster_update",
                            "monster_data": monster_data
                        }))
            
            elif data["type"] == "monster_despawn":
                net_id = data.get("net_id")
                
                if not net_id:
                    continue
                
                # Remove monster
                if net_id in monsters:
                    print(f"Monster despawned: {net_id}")
                    del monsters[net_id]
                
                # Broadcast despawn to all other clients
                for cid, client in clients.items():
                    if cid != client_id:
                        await client["websocket"].send(json.dumps({
                            "type": "monster_despawn",
                            "net_id": net_id
                        }))
            
            elif data["type"] == "get_player_monsters":
                # Client is requesting their monsters list
                username = clients[client_id]["username"]
                authenticated = clients[client_id]["authenticated"]
                
                if not authenticated or username.startswith("Guest"):
                    # Guest users have no saved monsters
                    await websocket.send(json.dumps({
                        "type": "player_monsters_list",
                        "monsters": []
                    }))
                    print(f"Sent empty monster list to guest: {username}")
                else:
                    # Get user's monsters from their data file
                    user_monsters = get_user_monsters(username)
                    
                    # Automatically set texture for countryball monsters to {username}_countryball
                    for monster in user_monsters:
                        if monster.get("species") == "countryball":
                            monster["texture"] = f"{username}_countryball"
                            print(f"Set countryball texture to: {username}_countryball")
                    
                    await websocket.send(json.dumps({
                        "type": "player_monsters_list",
                        "monsters": user_monsters
                    }))
                    print(f"Sent {len(user_monsters)} monster(s) to {username}")
    
    except websockets.exceptions.ConnectionClosed:
        pass
    finally:
        # Remove client
        if client_id in clients:
            username = clients[client_id]["username"]
            del clients[client_id]
            
            # Remove all monsters owned by this client
            monsters_to_remove = []
            for net_id, monster_data in monsters.items():
                if monster_data["owner_id"] == client_id:
                    monsters_to_remove.append(net_id)
            
            # Despawn monsters and notify clients
            for net_id in monsters_to_remove:
                print(f"Despawning monster {net_id} (owner {username} disconnected)")
                del monsters[net_id]
                
                # Notify all remaining clients to despawn this monster
                for cid, client in clients.items():
                    try:
                        await client["websocket"].send(json.dumps({
                            "type": "monster_despawn",
                            "net_id": net_id
                        }))
                    except:
                        pass  # Client might be disconnecting too
            
            # Notify all clients about player leaving
            for cid, client in clients.items():
                await client["websocket"].send(json.dumps({
                    "type": "player_left",
                    "player_id": client_id
                }))
                
                await client["websocket"].send(json.dumps({
                    "type": "system_message",
                    "message": f"{username} has left the server"
                }))

async def weather_monitor():
    """Monitor world_environment.json for changes and broadcast updates"""
    last_weather = None
    
    while True:
        try:
            current_env = get_world_environment()
            current_weather = current_env.get("weather", {"type": "clear"})
            
            # Check if weather has changed
            if current_weather != last_weather:
                print(f"Weather changed from {last_weather} to {current_weather}")
                await broadcast_weather_update()
                last_weather = current_weather
            
            # Check every 5 seconds
            await asyncio.sleep(5)
        except Exception as e:
            print(f"Error in weather monitor: {e}")
            await asyncio.sleep(5)

async def main():
    import ssl
    import os
    
    # Load environment variables from .env if present
    env_file = os.path.join(os.getcwd(), '.env')
    if os.path.exists(env_file):
        with open(env_file, 'r') as ef:
            for line in ef:
                if '=' in line:
                    k, v = line.strip().split('=', 1)
                    os.environ.setdefault(k, v)
    SSL_CERT_PATH = os.environ.get('SSL_CERT_PATH', None)
    SSL_KEY_PATH = os.environ.get('SSL_KEY_PATH', None)
    
    ssl_context = None
    protocol = "ws"
    
    if SSL_CERT_PATH and SSL_KEY_PATH and os.path.exists(SSL_CERT_PATH):
        ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ssl_context.load_cert_chain(SSL_CERT_PATH, SSL_KEY_PATH)
        protocol = "wss"
        print(f"SSL enabled with certificate: {SSL_CERT_PATH}")
    else:
        print("SSL disabled (no certificates found). Set SSL_CERT_PATH and SSL_KEY_PATH environment variables.")
    
    # Start all servers and monitors concurrently
    game_server = websockets.serve(
        handle_client, 
        MAIN_SERVER_HOST, 
        MAIN_SERVER_PORT,
        max_size=MAX_MESSAGE_SIZE,
        max_queue=MAX_QUEUE_SIZE,
        ssl=ssl_context
    )
    voice_server = voice_chat_server.start_server(ssl_context)
    weather_task = weather_monitor()
    
    print("Starting unified server with:")
    print(f"- Game Server (Lobby) on {protocol}://{MAIN_SERVER_HOST}:{MAIN_SERVER_PORT}")
    print(f"- Voice Chat Server on {protocol}://{MAIN_SERVER_HOST}:{VOICE_CHAT_SERVER_PORT}")
    print(f"- Weather Monitor (checks {WORLD_ENVIRONMENT_FILE} every 5s)")
    print(f"- Place Servers will spawn dynamically on ports {PLACE_SERVER_START_PORT}+")
    
    # Run all services concurrently
    await asyncio.gather(
        game_server,
        voice_server,
        weather_task
    )

if __name__ == "__main__":
    asyncio.run(main())
